Testing version stuff

diff --git a/.github/workflows/snap.yml b/.github/workflows/snap.yml
--- a/.github/workflows/snap.yml
+++ b/.github/workflows/snap.yml
@@ -30,24 +30,31 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Build ${{ env.SNAP_NAME }} Snap
-        id: build-snap
-        uses: snapcore/action-build@v1.1.3
+      - name: Test version stuff local
+        run: |
+          echo GITHUB_REF=$GITHUB_REF
+          echo GITHUB_REF_NAME=$GITHUB_REF_NAME
+          echo GITHUB_REF_TYPE=$GITHUB_REF_TYPE
+          git describe --tags --always
 
-      - uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: snapcraft-logs
-          path: |
-            ~/.cache/snapcraft/log/
-            ~/.local/state/snapcraft/log/
-            ${{ env.SNAP_NAME }}_*.txt
+      # - name: Build ${{ env.SNAP_NAME }} Snap
+      #   id: build-snap
+      #   uses: snapcore/action-build@v1.1.3
 
-      - name: Attach ${{ steps.build-snap.outputs.snap }} to GH workflow execution
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ steps.build-snap.outputs.snap }}
-          path: ${{ steps.build-snap.outputs.snap }}
+      # - uses: actions/upload-artifact@v3
+      #   if: failure()
+      #   with:
+      #     name: snapcraft-logs
+      #     path: |
+      #       ~/.cache/snapcraft/log/
+      #       ~/.local/state/snapcraft/log/
+      #       ${{ env.SNAP_NAME }}_*.txt
+
+      # - name: Attach ${{ steps.build-snap.outputs.snap }} to GH workflow execution
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: ${{ steps.build-snap.outputs.snap }}
+      #     path: ${{ steps.build-snap.outputs.snap }}
 
   remote-build:
     runs-on: ubuntu-latest
@@ -62,118 +69,125 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Set LP credentials for remote build
+      - name: Test version stuff remote
         run: |
-          lp_creds_path="$HOME/.local/share/snapcraft/"
-          mkdir -p $lp_creds_path
-          echo '${{ secrets.LP_CREDENTIALS }}' > ${lp_creds_path}/launchpad-credentials
-          git config --global user.email "${{ secrets.PEBBLE_DEV_MAILING_LIST}}"
-          git config --global user.name "pebble-dev"
+          echo GITHUB_REF=$GITHUB_REF
+          echo GITHUB_REF_NAME=$GITHUB_REF_NAME
+          echo GITHUB_REF_TYPE=$GITHUB_REF_TYPE
+          git describe --tags --always
 
-      - name: Build ${{ env.SNAP_NAME }} Snap for ${{ matrix.arch }}
-        id: build-snap
-        uses: snapcore/action-build@v1.1.3
-        with:
-          snapcraft-args: remote-build --build-for=${{ matrix.arch }} --launchpad-accept-public-upload
+  #     - name: Set LP credentials for remote build
+  #       run: |
+  #         lp_creds_path="$HOME/.local/share/snapcraft/"
+  #         mkdir -p $lp_creds_path
+  #         echo '${{ secrets.LP_CREDENTIALS }}' > ${lp_creds_path}/launchpad-credentials
+  #         git config --global user.email "${{ secrets.PEBBLE_DEV_MAILING_LIST}}"
+  #         git config --global user.name "pebble-dev"
 
-      - uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: snapcraft-logs
-          path: |
-            ~/.cache/snapcraft/log/
-            ~/.local/state/snapcraft/log/
-            ${{ env.SNAP_NAME }}_*.txt
+  #     - name: Build ${{ env.SNAP_NAME }} Snap for ${{ matrix.arch }}
+  #       id: build-snap
+  #       uses: snapcore/action-build@v1.1.3
+  #       with:
+  #         snapcraft-args: remote-build --build-for=${{ matrix.arch }} --launchpad-accept-public-upload
 
-      - name: Attach ${{ steps.build-snap.outputs.snap }} to GH workflow execution
-        uses: actions/upload-artifact@v3
-        if: steps.build-snap.outcome == 'success'
-        with:
-          name: ${{ steps.build-snap.outputs.snap }}
-          path: ${{ steps.build-snap.outputs.snap }}
+  #     - uses: actions/upload-artifact@v3
+  #       if: failure()
+  #       with:
+  #         name: snapcraft-logs
+  #         path: |
+  #           ~/.cache/snapcraft/log/
+  #           ~/.local/state/snapcraft/log/
+  #           ${{ env.SNAP_NAME }}_*.txt
 
-  test:
-    runs-on: ubuntu-latest
-    needs: [local-build, remote-build]
-    env:
-      # Testing is only enabled on amd64. We can add arm64 once we have such runners.
-      TEST_ON: amd64
-    if: |
-      always() &&
-      (needs.local-build.result == 'success' || needs.local-build.result == 'skipped') &&
-      (needs.remote-build.result == 'success' || needs.remote-build.result == 'skipped')
-    steps:
-      - uses: actions/download-artifact@v3
+  #     - name: Attach ${{ steps.build-snap.outputs.snap }} to GH workflow execution
+  #       uses: actions/upload-artifact@v3
+  #       if: steps.build-snap.outcome == 'success'
+  #       with:
+  #         name: ${{ steps.build-snap.outputs.snap }}
+  #         path: ${{ steps.build-snap.outputs.snap }}
 
-      - id: get-snap
-        run: echo "filename=$(find ${{ env.SNAP_NAME }}*${{ env.TEST_ON }}*snap/*)" >> $GITHUB_OUTPUT
+  # test:
+  #   runs-on: ubuntu-latest
+  #   needs: [local-build, remote-build]
+  #   env:
+  #     # Testing is only enabled on amd64. We can add arm64 once we have such runners.
+  #     TEST_ON: amd64
+  #   if: |
+  #     always() &&
+  #     (needs.local-build.result == 'success' || needs.local-build.result == 'skipped') &&
+  #     (needs.remote-build.result == 'success' || needs.remote-build.result == 'skipped')
+  #   steps:
+  #     - uses: actions/download-artifact@v3
 
-      - name: Install and test ${{ steps.get-snap.outputs.filename }}
-        run: |
-          set -ex
-          sudo snap install --dangerous --classic ${{ steps.get-snap.outputs.filename }}
+  #     - id: get-snap
+  #       run: echo "filename=$(find ${{ env.SNAP_NAME }}*${{ env.TEST_ON }}*snap/*)" >> $GITHUB_OUTPUT
 
-          # Make sure it is installed
-          pebble version --client
+  #     - name: Install and test ${{ steps.get-snap.outputs.filename }}
+  #       run: |
+  #         set -ex
+  #         sudo snap install --dangerous --classic ${{ steps.get-snap.outputs.filename }}
 
-          # Run smoke test
-          pebble enter --create-dirs exec echo Hello | grep Hello
+  #         # Make sure it is installed
+  #         pebble version --client
 
-  release:
-    runs-on: ubuntu-latest
-    needs: [test]
-    if: github.event_name != 'pull_request' && needs.test.result == 'success' && always()
-    strategy:
-      fail-fast: false
-      matrix:
-        arch: ["amd64", "arm64", "ppc64el", "armhf", "s390x"]
-    steps:
-      - uses: actions/download-artifact@v3
+  #         # Run smoke test
+  #         pebble enter --create-dirs exec echo Hello | grep Hello
 
-      - id: get-snap
-        run: echo "filename=$(find ${{ env.SNAP_NAME }}*${{ matrix.arch }}*snap/*)" >> $GITHUB_OUTPUT
+  # release:
+  #   runs-on: ubuntu-latest
+  #   needs: [test]
+  #   if: github.event_name != 'pull_request' && needs.test.result == 'success' && always()
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       arch: ["amd64", "arm64", "ppc64el", "armhf", "s390x"]
+  #   steps:
+  #     - uses: actions/download-artifact@v3
 
-      - name: Release ${{ steps.get-snap.outputs.filename }} to ${{ env.DEFAULT_TRACK }}/${{ env.DEFAULT_RISK }}
-        uses: snapcore/action-publish@v1
-        env:
-          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
-        with:
-          snap: ${{ steps.get-snap.outputs.filename }}
-          release: ${{ env.DEFAULT_TRACK }}/${{ env.DEFAULT_RISK }}
+  #     - id: get-snap
+  #       run: echo "filename=$(find ${{ env.SNAP_NAME }}*${{ matrix.arch }}*snap/*)" >> $GITHUB_OUTPUT
 
-  promote:
-    runs-on: ubuntu-latest
-    needs: [release]
-    if: github.event_name == 'release' && needs.release.result == 'success' && always()
-    strategy:
-      fail-fast: false
-      matrix:
-        arch: [amd64, arm64, ppc64el, armhf, s390x]
-    env:
-      TO_TRACK: latest
-      TO_RISK: candidate
-    steps:
-      - name: Install Snapcraft
-        run: sudo snap install snapcraft --classic
+  #     - name: Release ${{ steps.get-snap.outputs.filename }} to ${{ env.DEFAULT_TRACK }}/${{ env.DEFAULT_RISK }}
+  #       uses: snapcore/action-publish@v1
+  #       env:
+  #         SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
+  #       with:
+  #         snap: ${{ steps.get-snap.outputs.filename }}
+  #         release: ${{ env.DEFAULT_TRACK }}/${{ env.DEFAULT_RISK }}
 
-      - name: Get current ${{ matrix.arch }} ${{ env.SNAP_NAME }} snap in ${{ env.TO_TRACK }}/${{ env.TO_RISK }}
-        id: get-snap
-        env:
-          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
-        run: |
-          revision="$(snapcraft status ${{ env.SNAP_NAME }} \
-            --track ${{ env.DEFAULT_TRACK }} --arch ${{ matrix.arch }} \
-            | grep "${{ env.DEFAULT_RISK }}" | awk -F' ' '{print $3}')"
+  # promote:
+  #   runs-on: ubuntu-latest
+  #   needs: [release]
+  #   if: github.event_name == 'release' && needs.release.result == 'success' && always()
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       arch: [amd64, arm64, ppc64el, armhf, s390x]
+  #   env:
+  #     TO_TRACK: latest
+  #     TO_RISK: candidate
+  #   steps:
+  #     - name: Install Snapcraft
+  #       run: sudo snap install snapcraft --classic
 
-          echo "revision=$revision" >> $GITHUB_OUTPUT
+  #     - name: Get current ${{ matrix.arch }} ${{ env.SNAP_NAME }} snap in ${{ env.TO_TRACK }}/${{ env.TO_RISK }}
+  #       id: get-snap
+  #       env:
+  #         SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
+  #       run: |
+  #         revision="$(snapcraft status ${{ env.SNAP_NAME }} \
+  #           --track ${{ env.DEFAULT_TRACK }} --arch ${{ matrix.arch }} \
+  #           | grep "${{ env.DEFAULT_RISK }}" | awk -F' ' '{print $3}')"
 
-      # It would be easier to use `snapcraft promote`, but there's an error when trying
-      # to avoid the prompt with the "--yes" option:
-      # > 'latest/edge' is not a valid set value for --from-channel when using --yes.
-      - name: Promote ${{ env.SNAP_NAME }} snap rev${{ steps.get-snap.outputs.revision }} to ${{ env.TO_TRACK }}/${{ env.TO_RISK }}
-        env:
-          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
-        run: |
-          snapcraft release ${{ env.SNAP_NAME }} \
-            ${{ steps.get-snap.outputs.revision }} \
-            ${{ env.TO_TRACK }}/${{ env.TO_RISK }}
+  #         echo "revision=$revision" >> $GITHUB_OUTPUT
+
+  #     # It would be easier to use `snapcraft promote`, but there's an error when trying
+  #     # to avoid the prompt with the "--yes" option:
+  #     # > 'latest/edge' is not a valid set value for --from-channel when using --yes.
+  #     - name: Promote ${{ env.SNAP_NAME }} snap rev${{ steps.get-snap.outputs.revision }} to ${{ env.TO_TRACK }}/${{ env.TO_RISK }}
+  #       env:
+  #         SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
+  #       run: |
+  #         snapcraft release ${{ env.SNAP_NAME }} \
+  #           ${{ steps.get-snap.outputs.revision }} \
+  #           ${{ env.TO_TRACK }}/${{ env.TO_RISK }}
